# Generated by Django 5.1.6 on 2025-06-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_url',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='uploads/'),
        ),
    ]
